Word = [
  {"word": "abandon", "meanings": ["放棄する", "見捨てる", "退去する"]},
  {"word": "abolish", "meanings": ["廃止する", "撤廃する"]},
  {"word": "absorb", "meanings": ["吸収する", "取り込む", "夢中にさせる"]},
  {"word": "accelerate", "meanings": ["加速する", "促進する"]},
  {"word": "accomplish", "meanings": ["達成する", "成し遂げる"]},
  {"word": "accumulate", "meanings": ["蓄積する", "積み重ねる"]},
  {"word": "adhere", "meanings": ["固守する", "遵守する"]},
  {"word": "adopt", "meanings": ["採用する", "養子にする"]},
  {"word": "advance", "meanings": ["進む", "前進する", "昇進する"]},
  {"word": "advocate", "meanings": ["支持する", "擁護する"]},
  {"word": "allocate", "meanings": ["割り当てる", "配分する"]},
  {"word": "anticipate", "meanings": ["予測する", "期待する"]},
  {"word": "analyze", "meanings": ["分析する", "解析する"]},
  {"word": "appreciate", "meanings": ["感謝する", "評価する", "理解する"]},
  {"word": "assert", "meanings": ["断言する", "主張する"]},
  {"word": "assist", "meanings": ["助ける", "支援する"]},
  {"word": "attain", "meanings": ["達成する", "到達する"]},
  {"word": "boost", "meanings": ["押し上げる", "増加させる"]},
  {"word": "collaborate", "meanings": ["協力する", "共同作業する"]},
  {"word": "compile", "meanings": ["編纂する", "集める"]},
  {"word": "conclude", "meanings": ["結論を下す", "終結する"]},
  {"word": "confess", "meanings": ["告白する", "白状する"]},
  {"word": "contribute", "meanings": ["貢献する", "寄付する"]},
  {"word": "coordinate", "meanings": ["調整する", "組織する"]},
  {"word": "critique", "meanings": ["批評する", "評論する"]},
  {"word": "declare", "meanings": ["宣言する", "発表する"]},
  {"word": "derive", "meanings": ["得る", "導き出す", "由来する"]},
  {"word": "diminish", "meanings": ["減少する", "小さくなる"]},
  {"word": "distribute", "meanings": ["配布する", "分配する"]},
  {"word": "eliminate", "meanings": ["排除する", "除去する"]},
  {"word": "evaluate", "meanings": ["評価する", "査定する"]},
  {"word": "expand", "meanings": ["拡大する", "広げる"]},
  {"word": "explore", "meanings": ["探索する", "調査する"]},
  {"word": "facilitate", "meanings": ["容易にする", "促進する"]},
  {"word": "foster", "meanings": ["促進する", "育成する"]},
  {"word": "generate", "meanings": ["生み出す", "発生させる"]},
  {"word": "hinder", "meanings": ["妨げる", "邪魔する"]},
  {"word": "hypothesize", "meanings": ["仮定する", "推測する"]},
  {"word": "illustrate", "meanings": ["説明する", "図示する"]},
  {"word": "imagine", "meanings": ["想像する", "思い描く"]},
  {"word": "implement", "meanings": ["実行する", "履行する"]},
  {"word": "inquire", "meanings": ["問い合わせる", "尋ねる"]},
  {"word": "inspire", "meanings": ["触発する", "奮起させる"]},
  {"word": "interact", "meanings": ["相互作用する", "交流する"]},
  {"word": "investigate", "meanings": ["調査する", "捜査する"]},
  {"word": "justify", "meanings": ["正当化する", "弁解する"]},
  {"word": "maintain", "meanings": ["維持する", "保つ"]},
  {"word": "modify", "meanings": ["変更する", "修正する"]},
  {"word": "negotiate", "meanings": ["交渉する", "取り決める"]},
  {"word": "observe", "meanings": ["観察する", "見る"]},
  {"word": "participate", "meanings": ["参加する", "関与する"]},
  {"word": "predict", "meanings": ["予測する", "予言する"]},
  {"word": "promote", "meanings": ["促進する", "昇進させる"]},
  {"word": "reinforce", "meanings": ["強化する", "補強する"]},
  {"word": "research", "meanings": ["研究する", "調査する"]},
  {"word": "respond", "meanings": ["応答する", "返答する"]},
  {"word": "review", "meanings": ["レビューする", "再確認する"]},
  {"word": "satisfy", "meanings": ["満足させる", "満たす"]},
  {"word": "suggest", "meanings": ["提案する", "示唆する"]},
  {"word": "sustain", "meanings": ["維持する", "支える"]},
  {"word": "terminate", "meanings": ["終了する", "終わらせる"]},
  {"word": "utilize", "meanings": ["利用する", "活用する"]},
  {"word": "verify", "meanings": ["確認する", "検証する"]}
]